/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigDisco
 */

public class ConfigDisco {
  public static final String SERIALIZED_NAME_IDENTITY_U_R_L = "identityURL";
  @SerializedName(SERIALIZED_NAME_IDENTITY_U_R_L)
  private String identityURL;

  public static final String SERIALIZED_NAME_A_P_I_U_R_L = "APIURL";
  @SerializedName(SERIALIZED_NAME_A_P_I_U_R_L)
  private String APIURL;


  public ConfigDisco identityURL(String identityURL) {
    
    this.identityURL = identityURL;
    return this;
  }

   /**
   * Public URL of the &#x60;/identity&#x60; endpoint (ie. the URL that anyone can use to get the identity associated with a public key). 
   * @return identityURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://identity.mydomain.com/identity", value = "Public URL of the `/identity` endpoint (ie. the URL that anyone can use to get the identity associated with a public key). ")

  public String getIdentityURL() {
    return identityURL;
  }


  public void setIdentityURL(String identityURL) {
    this.identityURL = identityURL;
  }


  public ConfigDisco APIURL(String APIURL) {
    
    this.APIURL = APIURL;
    return this;
  }

   /**
   * Public URL of the &#x60;/api&#x60; endpoint (ie. the URL that correspond to the Woleet.ID Server API). 
   * @return APIURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://mydomain.com/api", value = "Public URL of the `/api` endpoint (ie. the URL that correspond to the Woleet.ID Server API). ")

  public String getAPIURL() {
    return APIURL;
  }


  public void setAPIURL(String APIURL) {
    this.APIURL = APIURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigDisco configDisco = (ConfigDisco) o;
    return Objects.equals(this.identityURL, configDisco.identityURL) &&
        Objects.equals(this.APIURL, configDisco.APIURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identityURL, APIURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigDisco {\n");
    sb.append("    identityURL: ").append(toIndentedString(identityURL)).append("\n");
    sb.append("    APIURL: ").append(toIndentedString(APIURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

