/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * OpenAPI spec version: 1.0.4
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.woleet.idserver.api.model.EnrollmentBase;
import io.woleet.idserver.api.model.KeyDeviceEnum;
import java.io.IOException;
import java.util.UUID;

/**
 * EnrollmentPost
 */

public class EnrollmentPost extends EnrollmentBase {
  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private UUID userId;

  public static final String SERIALIZED_NAME_TEST = "test";
  @SerializedName(SERIALIZED_NAME_TEST)
  private Boolean test;

  public EnrollmentPost userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Id of the enrolled user.
   * @return userId
  **/
  @ApiModelProperty(example = "feb37e23-d04e-4e71-bf53-1f1a75ba3a68", required = true, value = "Id of the enrolled user.")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public EnrollmentPost test(Boolean test) {
    this.test = test;
    return this;
  }

   /**
   * True if it&#39;s a test.
   * @return test
  **/
  @ApiModelProperty(value = "True if it's a test.")
  public Boolean getTest() {
    return test;
  }

  public void setTest(Boolean test) {
    this.test = test;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrollmentPost enrollmentPost = (EnrollmentPost) o;
    return Objects.equals(this.userId, enrollmentPost.userId) &&
        Objects.equals(this.test, enrollmentPost.test) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, test, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrollmentPost {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

