/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.woleet.idserver.api.model.KeyDeviceEnum;
import io.woleet.idserver.api.model.KeyStatusEnum;
import java.io.IOException;

/**
 * ExternalKeyPost
 */

public class ExternalKeyPost {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PUBLIC_KEY = "publicKey";
  @SerializedName(SERIALIZED_NAME_PUBLIC_KEY)
  private String publicKey;

  public static final String SERIALIZED_NAME_DEVICE = "device";
  @SerializedName(SERIALIZED_NAME_DEVICE)
  private KeyDeviceEnum device = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private KeyStatusEnum status = null;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  private Long expiration;

  public ExternalKeyPost name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Key name.
   * @return name
  **/
  @ApiModelProperty(example = "Jim Smith's key", required = true, value = "Key name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExternalKeyPost publicKey(String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Key address.
   * @return publicKey
  **/
  @ApiModelProperty(example = "1HA79GnnZdHLZBMBQusXcgPEeMcrpnWahb", required = true, value = "Key address.")
  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public ExternalKeyPost device(KeyDeviceEnum device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @ApiModelProperty(value = "")
  public KeyDeviceEnum getDevice() {
    return device;
  }

  public void setDevice(KeyDeviceEnum device) {
    this.device = device;
  }

  public ExternalKeyPost status(KeyStatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public KeyStatusEnum getStatus() {
    return status;
  }

  public void setStatus(KeyStatusEnum status) {
    this.status = status;
  }

  public ExternalKeyPost expiration(Long expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Key expiration date (Unix ms timestamp). 
   * @return expiration
  **/
  @ApiModelProperty(example = "1569542400000", value = "Key expiration date (Unix ms timestamp). ")
  public Long getExpiration() {
    return expiration;
  }

  public void setExpiration(Long expiration) {
    this.expiration = expiration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalKeyPost externalKeyPost = (ExternalKeyPost) o;
    return Objects.equals(this.name, externalKeyPost.name) &&
        Objects.equals(this.publicKey, externalKeyPost.publicKey) &&
        Objects.equals(this.device, externalKeyPost.device) &&
        Objects.equals(this.status, externalKeyPost.status) &&
        Objects.equals(this.expiration, externalKeyPost.expiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, publicKey, device, status, expiration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalKeyPost {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

