/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * User identity provided as a set of X500 Distinguished Name attributes (see https://www.ietf.org/rfc/rfc4519.txt).
 */
@ApiModel(description = "User identity provided as a set of X500 Distinguished Name attributes (see https://www.ietf.org/rfc/rfc4519.txt).")

public class Identity {
  public static final String SERIALIZED_NAME_COMMON_NAME = "commonName";
  @SerializedName(SERIALIZED_NAME_COMMON_NAME)
  private String commonName;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "emailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  private String emailAddress;

  public static final String SERIALIZED_NAME_ORGANIZATION = "organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  private String organization;

  public static final String SERIALIZED_NAME_ORGANIZATIONAL_UNIT = "organizationalUnit";
  @SerializedName(SERIALIZED_NAME_ORGANIZATIONAL_UNIT)
  private String organizationalUnit;

  public static final String SERIALIZED_NAME_LOCALITY = "locality";
  @SerializedName(SERIALIZED_NAME_LOCALITY)
  private String locality;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public Identity commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * Common name (CN) (2.5.4.3)
   * @return commonName
  **/
  @ApiModelProperty(example = "Jim Smith", required = true, value = "Common name (CN) (2.5.4.3)")
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public Identity emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Email Address (EMAILADDRESS) (1.2.840.113549.1.9.1)
   * @return emailAddress
  **/
  @ApiModelProperty(example = "jim.smith@woleet.com", value = "Email Address (EMAILADDRESS) (1.2.840.113549.1.9.1)")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public Identity organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Organization name (O) (2.5.4.10)
   * @return organization
  **/
  @ApiModelProperty(example = "Woleet", value = "Organization name (O) (2.5.4.10)")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public Identity organizationalUnit(String organizationalUnit) {
    this.organizationalUnit = organizationalUnit;
    return this;
  }

   /**
   * Organizational unit name (OU) (2.5.4.11)
   * @return organizationalUnit
  **/
  @ApiModelProperty(example = "Sales", value = "Organizational unit name (OU) (2.5.4.11)")
  public String getOrganizationalUnit() {
    return organizationalUnit;
  }

  public void setOrganizationalUnit(String organizationalUnit) {
    this.organizationalUnit = organizationalUnit;
  }

  public Identity locality(String locality) {
    this.locality = locality;
    return this;
  }

   /**
   * Locality name (L) (2.5.4.7)
   * @return locality
  **/
  @ApiModelProperty(example = "Rennes", value = "Locality name (L) (2.5.4.7)")
  public String getLocality() {
    return locality;
  }

  public void setLocality(String locality) {
    this.locality = locality;
  }

  public Identity country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country code (C) (2.5.4.6)
   * @return country
  **/
  @ApiModelProperty(example = "FR", value = "Country code (C) (2.5.4.6)")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Identity identity = (Identity) o;
    return Objects.equals(this.commonName, identity.commonName) &&
        Objects.equals(this.emailAddress, identity.emailAddress) &&
        Objects.equals(this.organization, identity.organization) &&
        Objects.equals(this.organizationalUnit, identity.organizationalUnit) &&
        Objects.equals(this.locality, identity.locality) &&
        Objects.equals(this.country, identity.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonName, emailAddress, organization, organizationalUnit, locality, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Identity {\n");
    
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationalUnit: ").append(toIndentedString(organizationalUnit)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

