/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of entity holding the private key.&lt;br&gt; - &#x60;server&#x60;: the server (Woleet.ID Server or equivalent)&lt;br&gt; - &#x60;user&#x60;: the user (eg. by using a Ledger Nano S or Woleet.ID Mobile or equivalent) 
 */
@JsonAdapter(KeyHolderEnum.Adapter.class)
public enum KeyHolderEnum {
  
  SERVER("server"),
  
  USER("user");

  private String value;

  KeyHolderEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static KeyHolderEnum fromValue(String value) {
    for (KeyHolderEnum b : KeyHolderEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<KeyHolderEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final KeyHolderEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public KeyHolderEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return KeyHolderEnum.fromValue(value);
    }
  }
}

