/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ServerPublicInfo
 */

public class ServerPublicInfo {
  public static final String SERIALIZED_NAME_LOGO_U_R_L = "logoURL";
  @SerializedName(SERIALIZED_NAME_LOGO_U_R_L)
  private String logoURL;

  public static final String SERIALIZED_NAME_HT_M_L_FRAME = "HTMLFrame";
  @SerializedName(SERIALIZED_NAME_HT_M_L_FRAME)
  private String htMLFrame;

  public ServerPublicInfo logoURL(String logoURL) {
    this.logoURL = logoURL;
    return this;
  }

   /**
   * The URL of the logo that will be displayed in the sign in page. 
   * @return logoURL
  **/
  @ApiModelProperty(example = "https://mydomain.com/logo.svg", value = "The URL of the logo that will be displayed in the sign in page. ")
  public String getLogoURL() {
    return logoURL;
  }

  public void setLogoURL(String logoURL) {
    this.logoURL = logoURL;
  }

  public ServerPublicInfo htMLFrame(String htMLFrame) {
    this.htMLFrame = htMLFrame;
    return this;
  }

   /**
   * The HTML frame that will be displayed in the sign in page. 
   * @return htMLFrame
  **/
  @ApiModelProperty(example = "Hello World", value = "The HTML frame that will be displayed in the sign in page. ")
  public String getHtMLFrame() {
    return htMLFrame;
  }

  public void setHtMLFrame(String htMLFrame) {
    this.htMLFrame = htMLFrame;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerPublicInfo serverPublicInfo = (ServerPublicInfo) o;
    return Objects.equals(this.logoURL, serverPublicInfo.logoURL) &&
        Objects.equals(this.htMLFrame, serverPublicInfo.htMLFrame);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logoURL, htMLFrame);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerPublicInfo {\n");
    
    sb.append("    logoURL: ").append(toIndentedString(logoURL)).append("\n");
    sb.append("    htMLFrame: ").append(toIndentedString(htMLFrame)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

