/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * The version of the OpenAPI document: 1.2.4
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * User role.&lt;br&gt; - &#x60;user&#x60;: a user can sign using his keys&lt;br&gt; - &#x60;manager&#x60;: a manager can manage user and seal identities and keys&lt;br&gt; - &#x60;admin&#x60;: an administrator can do everything on the server 
 */
@JsonAdapter(UserRoleEnum.Adapter.class)
public enum UserRoleEnum {
  
  USER("user"),
  
  MANAGER("manager"),
  
  ADMIN("admin");

  private String value;

  UserRoleEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserRoleEnum fromValue(String value) {
    for (UserRoleEnum b : UserRoleEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UserRoleEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserRoleEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UserRoleEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UserRoleEnum.fromValue(value);
    }
  }
}

