/*
 * Woleet.ID Server
 * This is Woleet.ID Server API documentation.
 *
 * OpenAPI spec version: 1.0.4
 * Contact: contact@woleet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.woleet.idserver.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.woleet.idserver.api.model.FullIdentity;
import io.woleet.idserver.api.model.UserPut;
import io.woleet.idserver.api.model.UserRoleEnum;
import io.woleet.idserver.api.model.UserStatusEnum;
import java.io.IOException;
import java.util.UUID;

/**
 * UserPost
 */

public class UserPost extends UserPut {
  public static final String SERIALIZED_NAME_SEND_KEY_ENROLMENT_MAIL = "sendKeyEnrolmentMail";
  @SerializedName(SERIALIZED_NAME_SEND_KEY_ENROLMENT_MAIL)
  private Boolean sendKeyEnrolmentMail;

  public static final String SERIALIZED_NAME_CREATE_DEFAULT_KEY = "createDefaultKey";
  @SerializedName(SERIALIZED_NAME_CREATE_DEFAULT_KEY)
  private Boolean createDefaultKey;

  public UserPost sendKeyEnrolmentMail(Boolean sendKeyEnrolmentMail) {
    this.sendKeyEnrolmentMail = sendKeyEnrolmentMail;
    return this;
  }

   /**
   * If true send an enrolment mail.
   * @return sendKeyEnrolmentMail
  **/
  @ApiModelProperty(required = true, value = "If true send an enrolment mail.")
  public Boolean getSendKeyEnrolmentMail() {
    return sendKeyEnrolmentMail;
  }

  public void setSendKeyEnrolmentMail(Boolean sendKeyEnrolmentMail) {
    this.sendKeyEnrolmentMail = sendKeyEnrolmentMail;
  }

  public UserPost createDefaultKey(Boolean createDefaultKey) {
    this.createDefaultKey = createDefaultKey;
    return this;
  }

   /**
   * If true create a key holded by the server when this user is created.
   * @return createDefaultKey
  **/
  @ApiModelProperty(required = true, value = "If true create a key holded by the server when this user is created.")
  public Boolean getCreateDefaultKey() {
    return createDefaultKey;
  }

  public void setCreateDefaultKey(Boolean createDefaultKey) {
    this.createDefaultKey = createDefaultKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPost userPost = (UserPost) o;
    return Objects.equals(this.sendKeyEnrolmentMail, userPost.sendKeyEnrolmentMail) &&
        Objects.equals(this.createDefaultKey, userPost.createDefaultKey) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sendKeyEnrolmentMail, createDefaultKey, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPost {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    sendKeyEnrolmentMail: ").append(toIndentedString(sendKeyEnrolmentMail)).append("\n");
    sb.append("    createDefaultKey: ").append(toIndentedString(createDefaultKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

