version: '3.4'

services:
  wid-client:
    volumes:
      - ${WOLEET_ID_SERVER_HTTP_TLS_CERTIFICATE:?Undefined WOLEET_ID_SERVER_HTTP_TLS_CERTIFICATE}:/etc/nginx/ssl/certificate.crt:ro
      - ${WOLEET_ID_SERVER_HTTP_TLS_KEY:?Undefined WOLEET_ID_SERVER_HTTP_TLS_KEY}:/etc/nginx/ssl/certificate.key:ro
    depends_on:
      - wid-server
    restart: "${WOLEET_ID_SERVER_RESTART_POLICY:-on-failure}"

  wid-server:
    stdin_open: true
    tty: true
    environment:
      WOLEET_ID_SERVER_CACHE_TYPE: ${WOLEET_ID_SERVER_CACHE_TYPE:-local}
      WOLEET_ID_SERVER_OIDC_KEY: ${WOLEET_ID_SERVER_OIDC_KEY:-random}
    networks:
      - postgres-server
    depends_on:
      - wid-postgres
    restart: "${WOLEET_ID_SERVER_RESTART_POLICY:-on-failure}"

  wid-postgres:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: ${WOLEET_ID_SERVER_POSTGRES_DB:-wid}
      POSTGRES_USER: ${WOLEET_ID_SERVER_POSTGRES_USER:-pguser}
      POSTGRES_PASSWORD: ${WOLEET_ID_SERVER_POSTGRES_PASSWORD:-pass}
    volumes:
      - ${WOLEET_ID_SERVER_DATA_DIR:-./db}:/var/lib/postgresql/data:rw
    networks:
      - postgres-server
    restart: "${WOLEET_ID_SERVER_RESTART_POLICY:-on-failure}"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

networks:
  client-server:
    driver: bridge
  postgres-server:
    driver: bridge
