version: '3.4'
services:
  wid-client:
    secrets:
      - source: ssl-cert
        target: /etc/nginx/ssl/certificate.crt
      - source: ssl-key
        target: /etc/nginx/ssl/certificate.key
    deploy:
      mode: replicated
      replicas: ${WOLEET_ID_SERVER_CLIENT_REPLICAS:-2}
      update_config:
        order: stop-first
      restart_policy:
        condition: "${WOLEET_ID_SERVER_RESTART_POLICY:-any}"
    healthcheck:
      test: "curl -fqk https://localhost:3000 > /dev/null 2>&1"
      interval: 30s
      timeout: 10s
      retries: 3
  wid-server:
    environment:
      WOLEET_ID_SERVER_CACHE_TYPE: ${WOLEET_ID_SERVER_CACHE_TYPE:-redis}
      WOLEET_ID_SERVER_REDIS_HOST: ${WOLEET_ID_SERVER_REDIS_HOST:-redis}
      WOLEET_ID_SERVER_REDIS_PORT: ${WOLEET_ID_SERVER_REDIS_PORT:-6379}
    secrets:
      - source: encryption-secret
        target: /usr/src/app/dist/src/encryption_secret
    networks:
      - redis-server
    deploy:
      mode: replicated
      replicas: ${WOLEET_ID_SERVER_SERVER_REPLICAS:-2}
      update_config:
        order: stop-first
      restart_policy:
        condition: "${WOLEET_ID_SERVER_RESTART_POLICY:-any}"
    healthcheck:
      test: "curl -fq -H 'X-Forwarded-Proto:https' http://localhost:3000/check > /dev/null 2>&1"
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: redis:6.0-alpine
    networks:
      - redis-server
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "${WOLEET_ID_SERVER_RESTART_POLICY:-any}"
    healthcheck:
      test: "redis-cli ping > /dev/null 2>&1"
      interval: 30s
      timeout: 10s
      retries: 3
secrets:
  encryption-secret:
    external:
      name : ${WOLEET_ID_SERVER_PROJECT_NAME:-woleetid-server}_encryption-secret
  ssl-cert:
    file: ${WOLEET_ID_SERVER_HTTP_TLS_CERTIFICATE:?Undefined WOLEET_ID_SERVER_HTTP_TLS_CERTIFICATE}
  ssl-key:
    file: ${WOLEET_ID_SERVER_HTTP_TLS_KEY:?Undefined WOLEET_ID_SERVER_HTTP_TLS_KEY}
networks:
  client-server:
    driver: overlay
  redis-server:
    driver: overlay
