export function serializeServerConfig(config: InternalServerConfigObject): ApiServerConfig {
  const {
    fallbackOnDefaultKey,
    defaultKeyId,
    identityURL,
    logoURL,
    HTMLFrame,
    allowUserToSign,
    enableOpenIDConnect,
    openIDConnectURL,
    openIDConnectClientId,
    openIDConnectClientSecret,
    openIDConnectClientRedirectURL,
    enableOIDCP,
    OIDCPInterfaceURL,
    OIDCPProviderURL,
    OIDCPIssuerURL,
    OIDCPClients,
    keyExpirationOffset,
    enrollmentExpirationOffset,
    enableSMTP,
    SMTPConfig,
    webClientURL,
    mailResetPasswordTemplate,
    mailOnboardingTemplate,
    mailKeyEnrollmentTemplate,
    TCU,
    contact,
    organizationName,
    proofDeskAPIURL,
    proofDeskAPIToken,
    enableProofDesk
  } = config;

  return {
    fallbackOnDefaultKey,
    defaultKeyId,
    identityURL,
    logoURL,
    HTMLFrame,
    allowUserToSign,
    enableOpenIDConnect: enableOpenIDConnect,
    openIDConnectURL,
    openIDConnectClientId,
    openIDConnectClientSecret,
    openIDConnectClientRedirectURL,
    enableOIDCP,
    OIDCPInterfaceURL,
    OIDCPProviderURL,
    OIDCPIssuerURL,
    OIDCPClients,
    keyExpirationOffset,
    enrollmentExpirationOffset,
    enableSMTP: enableSMTP,
    SMTPConfig,
    webClientURL,
    mailResetPasswordTemplate,
    mailOnboardingTemplate,
    mailKeyEnrollmentTemplate,
    TCU,
    contact,
    organizationName,
    proofDeskAPIURL,
    proofDeskAPIToken,
    enableProofDesk: enableProofDesk
  };
}
