name: build-and-push-docker-images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: docker_setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_WIDS_USERNAME }}
          password: ${{ secrets.DOCKERHUB_WIDS_TOKEN }}

      - name: Get Tag
        id: github_tag
        run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"

      - name: Get API version
        id: swagger_api_version
        run: echo "::set-output name=WOLEET_ID_SERVER_API_VERSION::$(cat swagger.yaml | grep 'version' | grep -oE '([[:digit:]]+.?)+')"

      - name: Build and push Client
        id: docker_build_push_client
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.client
          push: true
          tags: |
            wids/client:latest
            wids/client:${{ steps.github_tag.outputs.TAG }}

      - name: Build and push Server
        id: docker_build_push_server
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.server
          push: true
          build-args: |
            WOLEET_ID_SERVER_API_VERSION_BUILDTIME=${{ steps.swagger_api_version.outputs.WOLEET_ID_SERVER_API_VERSION }}
          tags: |
            wids/server:latest
            wids/server:${{ steps.github_tag.outputs.TAG }}
